#ifndef BZ_ITEM_NAMES_HPP
#define BZ_ITEM_NAMES_HPP

#include <string>
#include <unordered_map>

const std::unordered_map<std::string, std::string> item_names = {
    { "ACACIA_STAIRS", "Acacia Wood Stairs" },
    { "ACACIA_FENCE", "Acacia Fence" },
    { "ACACIA_DOOR_ITEM", "Acacia Door" },
    { "AATROX_BATPHONE", "Maddox Batphone" },
    { "ANGLER_LEGGINGS", "Angler Leggings" },
    { "ANGLER_BOOTS", "Angler Boots" },
    { "ANGLER_HELMET", "Angler Helmet" },
    { "ANGLER_CHESTPLATE", "Angler Chestplate" },
    { "ANVIL", "Anvil" },
    { "ANVIL:1", "Slightly Damaged Anvil" },
    { "ANVIL:2", "Very Damaged Anvil" },
    { "ARMOR_OF_MAGMA_HELMET", "Armor of Magma Helmet" },
    { "ARMOR_OF_MAGMA_CHESTPLATE", "Armor of Magma Chestplate" },
    { "ARMOR_OF_MAGMA_BOOTS", "Armor of Magma Boots" },
    { "ARMOR_SHOWCASE", "Armor Stand" },
    { "ARMOR_STAND", "Armor Stand" },
    { "ARROW", "Arrow" },
    { "ASPECT_OF_THE_DRAGON", "Aspect of the Dragons" },
    { "ASPECT_OF_THE_END", "Aspect of the End" },
    { "ARMOR_OF_MAGMA_LEGGINGS", "Armor of Magma Leggings" },
    { "APPLE", "Apple" },
    { "BAIT_RING", "Bait Ring" },
    { "AUGER_ROD", "Auger Rod" },
    { "BAKED_POTATO", "Baked Potato" },
    { "ARTIFACT_POTION_AFFINITY", "Potion Affinity Artifact" },
    { "BARRIER", "Barrier" },
    { "BATTLE_DISC", "Battle Disc" },
    { "BAT_FIREWORK", "Bat Firework" },
    { "AUTO_SMELTER", "Auto Smelter" },
    { "BAT_ARTIFACT", "Bat Artifact" },
    { "BAT_PERSON_BOOTS", "Bat Person Boots" },
    { "BAT_PERSON_LEGGINGS", "Bat Person Leggings" },
    { "BAT_TALISMAN", "Bat Talisman" },
    { "BAT_PERSON_HELMET", "Bat Person Helmet" },
    { "BAT_PERSON_CHESTPLATE", "Bat Person Chestplate" },
    { "BEACH_BALL", "Beach Ball" },
    { "BEACH_CHAIR", "Beach Chair" },
    { "BEACH_BALL_PERSONALITY", "Beach Ball Minion Skin" },
    { "BEACH_CHAIR_PLUS", "Beach Chair+" },
    { "BED", "Bed" },
    { "BAT_RING", "Bat Ring" },
    { "BEST_WEAPON_RACK", "Weapon Rack+" },
    { "BEE_PERSONALITY", "Bee Minion Skin" },
    { "BIRCH_DOOR_ITEM", "Birch Door" },
    { "BIRCH_FENCE", "Birch Fence" },
    { "BIRCH_FENCE_GATE", "Birch Fence Gate" },
    { "BIRCH_FOREST_BIOME_STICK", "Birch Forest Biome Stick" },
    { "BIRCH_WOOD_STAIRS", "Birch Wood Stairs" },
    { "BEACON", "Beacon Block" },
    { "BITTER_ICE_TEA", "Bitter Ice Tea" },
    { "BLAZE_CHESTPLATE", "Blaze Chestplate" },
    { "BLAZE_BOOTS", "Blaze Boots" },
    { "BIG_XTREE", "Tall Holiday Tree" },
    { "BLAZE_LEGGINGS", "Blaze Leggings" },
    { "BEHEADED_HORROR", "Beheaded Horror" },
    { "BLAZE_HELMET", "Blaze Helmet" },
    { "BLESSED_BAIT", "Blessed Bait" },
    { "BLOBFISH_HAT", "Blobfish Hat" },
    { "BLAZE_POWDER", "Blaze Powder" },
    { "BAT_THE_FISH", "Bat the Fish" },
    { "BLAZE_ROD", "Blaze Rod" },
    { "BLAZE_HAT", "Blaze Hat" },
    { "BOOKCASE", "Bookcase" },
    { "BOOK", "Book" },
    { "BOOKSHELF", "Bookshelf" },
    { "BOOTS_OF_THE_PACK", "Boots of the Pack" },
    { "BOOK_AND_QUILL", "Book and Quill" },
    { "BLUE_ICE_HUNK", "Hunk of Blue Ice" },
    { "BOWL", "Bowl" },
    { "BOAT", "Boat" },
    { "BONE", "Bone" },
    { "BREWING_PLUS", "Brewing+" },
    { "BREWING_STAND_ITEM", "Brewing Stand" },
    { "BRICK_STAIRS", "Brick Stairs" },
    { "BREAD", "Bread" },
    { "BRICK", "Bricks" },
    { "BRIDGE_EGG", "Bridge Egg" },
    { "BUCKET", "Bucket" },
    { "BROWN_MUSHROOM", "Brown Mushroom" },
    { "BOTTLE_OF_JYRRE", "Bottle of Jyrre" },
    { "BUNNY", "Bunny" },
    { "BOW", "Bow" },
    { "BUDGET_HOPPER", "Budget Hopper" },
    { "BUNNY_JERRY", "Bunny Jerry" },
    { "CACTUS", "Cactus" },
    { "CACTUS_BOOTS", "Cactus Boots" },
    { "BUNNY_PERSONALITY", "Bunny Minion Skin" },
    { "CAKE", "Cake" },
    { "CAMPFIRE", "Fire Pit" },
    { "CANDLE_ARCH", "Candle Arch" },
    { "CACTUS_HELMET", "Cactus Helmet" },
    { "CANDY_BOWL", "Candy Bowl" },
    { "CACTUS_LEGGINGS", "Cactus Leggings" },
    { "CACTUS_CHESTPLATE", "Cactus Chestplate" },
    { "CARPENTRY_BENCH", "Carpentry Table" },
    { "CARPET", "Carpet" },
    { "CARPET:10", "Purple Carpet" },
    { "CARPET:11", "Blue Carpet" },
    { "CARPET:12", "Brown Carpet" },
    { "CARPET:13", "Green Carpet" },
    { "CARPET:14", "Red Carpet" },
    { "CARPET:15", "Black Carpet" },
    { "CARPET:2", "Magenta Carpet" },
    { "CARPET:3", "Light Blue Carpet" },
    { "CARPET:4", "Yellow Carpet" },
    { "CARPET:5", "Lime Carpet" },
    { "CARPET:7", "Gray Carpet" },
    { "CARPET:8", "Light Gray Carpet" },
    { "CARROT", "Carrots" },
    { "CARROT_BAIT", "Carrot Bait" },
    { "CANDY_RING", "Candy Ring" },
    { "CARROT_STICK", "Carrot on a Stick" },
    { "CAULDRON", "Cauldron" },
    { "CAULDRON_ITEM", "Cauldron" },
    { "CHAINMAIL_BOOTS", "Chainmail Boots" },
    { "CHAINMAIL_CHESTPLATE", "Chainmail Chestplate" },
    { "CHAINMAIL_HELMET", "Chainmail Helmet" },
    { "CHAINMAIL_LEGGINGS", "Chainmail Leggings" },
    { "CANDY_ARTIFACT", "Candy Artifact" },
    { "CARROT_ITEM", "Carrot" },
    { "CHAMP_ROD", "Rod of Champions" },
    { "CHEAP_COFFEE", "Cheap Coffee" },
    { "CHEAP_TUXEDO_CHESTPLATE", "Cheap Tuxedo Jacket" },
    { "CHEAP_TUXEDO_LEGGINGS", "Cheap Tuxedo Pants" },
    { "CHEST", "Chest" },
    { "CHESTPLATE_OF_THE_PACK", "Chestplate of the Pack" },
    { "CHEST_SHELVES", "Chest Storage" },
    { "CHALLENGE_ROD", "Challenging Rod" },
    { "BROKEN_PIGGY_BANK", "Broken Piggy Bank" },
    { "CHICKEN_HEAD", "Chicken Head" },
    { "CHEAP_TUXEDO_BOOTS", "Cheap Tuxedo Oxfords" },
    { "CLAY_BRICK", "Brick" },
    { "CHICK_NEST", "Chick Nest" },
    { "CLOWNFISH_HAT", "Clownfish Hat" },
    { "CLAY", "Clay" },
    { "COAL:1", "Charcoal" },
    { "CLAY_BALL", "Clay" },
    { "COAL_ORE", "Coal Ore" },
    { "COAL", "Coal" },
    { "COBBLESTONE_STAIRS", "Cobblestone Stairs" },
    { "COBBLE_WALL", "Cobblestone Wall" },
    { "COBBLE_WALL:1", "Mossy Cobblestone Wall" },
    { "COFFEE_TABLE", "Coffee Table" },
    { "COAL_BLOCK", "Block of Coal" },
    { "CANDY_TALISMAN", "Candy Talisman" },
    { "COLD_ONES", "Cola Cooler" },
    { "COMPASS", "Compass" },
    { "COOKED_BEEF", "Cooked Beef" },
    { "COOKED_CHICKEN", "Cooked Chicken" },
    { "COOKED_FISH", "Cooked Fish" },
    { "COOKED_FISH:1", "Cooked Salmon" },
    { "COOKIE", "Cookie" },
    { "COW_HEAD", "Cow Head" },
    { "COIN_TALISMAN", "Talisman of Coins" },
    { "CRAFTING_PLUS", "Crafting Table+" },
    { "CREATIVE_MIND", "Creative Mind" },
    { "CREEPER_HAT", "Creeper Hat" },
    { "COBBLESTONE", "Cobblestone" },
    { "CLEAVER", "Cleaver" },
    { "CREEPER_LEGGINGS", "Creeper Pants" },
    { "CRYSTALLIZED_HEART", "Crystallized Heart" },
    { "CRYSTAL_FRAGMENT", "Crystal Fragment" },
    { "CRACKED_PIGGY_BANK", "Cracked Piggy Bank" },
    { "CRYSTAL_CHESTPLATE", "Crystal Chestplate" },
    { "DANGER_1_PORTAL", "Portal to Spider's Den" },
    { "CRYSTAL_BOOTS", "Crystal Boots" },
    { "DANGER_1_TRAVEL_SCROLL", "Travel Scroll to Spider's Den" },
    { "DANGER_2_PORTAL", "Portal to Blazing Fortress" },
    { "DANGER_2_TRAVEL_SCROLL", "Travel Scroll to Blazing Fortress" },
    { "DANGER_3_PORTAL", "Portal to The End" },
    { "DARK_BAIT", "Dark Bait" },
    { "DARK_OAK_DOOR_ITEM", "Dark Oak Door" },
    { "DARK_OAK_FENCE", "Dark Oak Fence" },
    { "DARK_OAK_STAIRS", "Dark Oak Wood Stairs" },
    { "DAYLIGHT_DETECTOR", "Daylight Detector" },
    { "CRYSTAL_HELMET", "Crystal Helmet" },
    { "CRYSTAL_LEGGINGS", "Crystal Leggings" },
    { "DEAD_BUSH_OF_LOVE", "Dead Bush of Love" },
    { "DEAD_BUSH", "Dead Bush" },
    { "DANGER_3_TRAVEL_SCROLL", "Travel Scroll to the End" },
    { "DEEP_OCEAN_BIOME_STICK", "Deep Ocean Biome Stick" },
    { "DESERT_BIOME_STICK", "Desert Biome Stick" },
    { "DECENT_BOW", "Decent Bow" },
    { "DESK", "Desk" },
    { "DECENT_COFFEE", "Decent Coffee" },
    { "DESERT_ISLAND", "Desert Island" },
    { "DEVOUR_RING", "Devour Ring" },
    { "DIAMOND_BARDING", "Diamond Horse Armor" },
    { "DIAMOND", "Diamond" },
    { "DAY_SAVER", "Day Saver" },
    { "COMPACTOR", "Compactor" },
    { "DIAMOND_CHEST", "Diamond Chest+" },
    { "DIAMOND_BLOCK", "Block of Diamond" },
    { "DIAMOND_HOE", "Diamond Hoe" },
    { "DIAMOND_AXE", "Diamond Axe" },
    { "DIAMOND_ORE", "Diamond Ore" },
    { "DIAMOND_CHESTPLATE", "Diamond Chestplate" },
    { "DIAMOND_HELMET", "Diamond Helmet" },
    { "DIAMOND_SPADE", "Diamond Shovel" },
    { "DIAMOND_SPREADING", "Diamond Spreading" },
    { "DIAMOND_SWORD", "Diamond Sword" },
    { "DINING_CHAIR", "Dining Chair" },
    { "DIAMOND_BOOTS", "Diamond Boots" },
    { "DIODE", "Repeater" },
    { "DINING_TABLE", "Dining Table" },
    { "DIRT:1", "Coarse Dirt" },
    { "DIGESTED_MOSQUITO", "Digested Mosquito" },
    { "DISPENSER", "Dispenser" },
    { "DIAMOND_LEGGINGS", "Diamond Leggings" },
    { "DIRT:2", "Podzol" },
    { "DIRT", "Dirt" },
    { "DIVER_BOOTS", "Diver's Boots" },
    { "DIVER_CHESTPLATE", "Diver's Shirt" },
    { "DIVER_HELMET", "Diver's Mask" },
    { "DOUBLE_PLANT", "Sunflower" },
    { "DOUBLE_PLANT:2", "Double Tallgrass" },
    { "DIVER_LEGGINGS", "Diver's Trunks" },
    { "DIVER_FRAGMENT", "Emperor's Skull" },
    { "DRAGON_NEST_TRAVEL_SCROLL", "Travel Scroll to Dragon's Nest" },
    { "DROPPER", "Dropper" },
    { "DOUBLE_PLANT:1", "Lilac" },
    { "DR_PAPER", "Dctr. Paper" },
    { "DOUBLE_PLANT:5", "Peony" },
    { "EDIBLE_MACE", "Edible Mace" },
    { "DIAMOND_PICKAXE", "Diamond Pickaxe" },
    { "DOUBLE_PLANT:4", "Rose Bush" },
    { "EFFICIENT_AXE", "Efficient Axe" },
    { "ELEGANT_TUXEDO_BOOTS", "Elegant Tuxedo Oxfords" },
    { "EASTER_BASKET", "Easter Basket" },
    { "ELEGANT_TUXEDO_CHESTPLATE", "Elegant Tuxedo Jacket" },
    { "ELEGANT_TUXEDO_LEGGINGS", "Elegant Tuxedo Pants" },
    { "EGG_PILE", "Egg Pile" },
    { "EGG", "Egg" },
    { "EMBER_FRAGMENT", "Ember Fragment" },
    { "EMBER_HELMET", "Ember Helmet" },
    { "EMERALD", "Emerald" },
    { "EMBER_ROD", "Ember Rod" },
    { "EMBER_BOOTS", "Ember Boots" },
    { "EMERALD_ARMOR_CHESTPLATE", "Emerald Armor Chestplate" },
    { "EMERALD_ARMOR_HELMET", "Emerald Armor Helmet" },
    { "EMERALD_ARMOR_BOOTS", "Emerald Armor Boots" },
    { "EMERALD_ARMOR_LEGGINGS", "Emerald Armor Leggings" },
    { "EMERALD_CHEST", "Emerald Chest+" },
    { "EMERALD_ORE", "Emerald Ore" },
    { "EMPTY_MAP", "Empty Map" },
    { "EMBER_LEGGINGS", "Ember Leggings" },
    { "ENCHANTED_ACACIA_LOG", "Enchanted Acacia Wood" },
    { "EMERALD_BLOCK", "Block of Emerald" },
    { "ENCHANTED_BIRCH_LOG", "Enchanted Birch Wood" },
    { "ENCHANTED_BLAZE_POWDER", "Enchanted Blaze Powder" },
    { "ENCHANTED_BLAZE_ROD", "Enchanted Blaze Rod" },
    { "ENCHANTED_BAKED_POTATO", "Enchanted Baked Potato" },
    { "ENCHANTED_BONE_MEAL", "Enchanted Bone Meal" },
    { "EMERALD_BLADE", "Emerald Blade" },
    { "EMBER_CHESTPLATE", "Ember Chestplate" },
    { "ENCHANTED_BOOK", "Enchanted Book" },
    { "ENCHANTED_CACTUS", "Enchanted Cactus" },
    { "ENCHANTED_BOOKSHELF", "Enchanted Bookshelf" },
    { "ENCHANTED_BROWN_MUSHROOM", "Enchanted Brown Mushroom" },
    { "ENCHANTED_CAKE", "Enchanted Cake" },
    { "ENCHANTED_CACTUS_GREEN", "Enchanted Cactus Green" },
    { "ENCHANTED_CHARCOAL", "Enchanted Charcoal" },
    { "ENCHANTED_BONE", "Enchanted Bone" },
    { "ENCHANTED_CLOWNFISH", "Enchanted Clownfish" },
    { "ENCHANTED_CARROT", "Enchanted Carrot" },
    { "ENCHANTED_BREAD", "Enchanted Bread" },
    { "ENCHANTED_COAL", "Enchanted Coal" },
    { "ENCHANTED_CARROT_STICK", "Enchanted Carrot on a Stick" },
    { "ENCHANTED_COOKED_FISH", "Enchanted Cooked Fish" },
    { "ENCHANTED_COOKED_MUTTON", "Enchanted Cooked Mutton" },
    { "ENCHANTED_COOKED_SALMON", "Enchanted Cooked Salmon" },
    { "ENCHANTED_COOKIE", "Enchanted Cookie" },
    { "ENCHANTED_COCOA", "Enchanted Cocoa Bean" },
    { "ENCHANTED_COAL_BLOCK", "Enchanted Block of Coal" },
    { "ENCHANTED_CLAY_BALL", "Enchanted Clay" },
    { "ENCHANTED_DANDELION", "Enchanted Dandelion" },
    { "ENCHANTED_DARK_OAK_LOG", "Enchanted Dark Oak Wood" },
    { "ENCHANTED_EMERALD", "Enchanted Emerald" },
    { "ENCHANTED_DIAMOND", "Enchanted Diamond" },
    { "ENCHANTED_EMERALD_BLOCK", "Enchanted Emerald Block" },
    { "ENCHANTED_DIAMOND_BLOCK", "Enchanted Diamond Block" },
    { "ENCHANTED_ENDSTONE", "Enchanted End Stone" },
    { "ENCHANTED_FEATHER", "Enchanted Feather" },
    { "ENCHANTED_EYE_OF_ENDER", "Enchanted Eye of Ender" },
    { "ENCHANTED_FIREWORK_ROCKET", "Enchanted Firework Rocket" },
    { "ENCHANTED_FERMENTED_SPIDER_EYE", "Enchanted Fermented Spider Eye" },
    { "ENCHANTED_FLINT", "Enchanted Flint" },
    { "ENCHANTED_GLISTERING_MELON", "Enchanted Glistering Melon" },
    { "ENCHANTED_GHAST_TEAR", "Enchanted Ghast Tear" },
    { "ENCHANTED_GLOWSTONE_DUST", "Enchanted Glowstone Dust" },
    { "ENCHANTED_GLOWSTONE", "Enchanted Glowstone" },
    { "ENCHANTED_GOLDEN_CARROT", "Enchanted Golden Carrot" },
    { "ENCHANTED_GOLD_BLOCK", "Enchanted Gold Block" },
    { "ENCHANTED_GOLD", "Enchanted Gold" },
    { "ENCHANTED_GUNPOWDER", "Enchanted Gunpowder" },
    { "ENCHANTED_HAY_BLOCK", "Enchanted Hay Bale" },
    { "ENCHANTED_COBBLESTONE", "Enchanted Cobblestone" },
    { "ENCHANTED_HUGE_MUSHROOM_1", "Enchanted Brown Mushroom Block" },
    { "ENCHANTED_GRILLED_PORK", "Enchanted Grilled Pork" },
    { "ENCHANTED_ICE", "Enchanted Ice" },
    { "ENCHANTED_INK_SACK", "Enchanted Ink Sack" },
    { "ENCHANTED_HUGE_MUSHROOM_2", "Enchanted Red Mushroom Block" },
    { "ENCHANTED_ENDER_PEARL", "Enchanted Ender Pearl" },
    { "ENCHANTED_JACK_O_LANTERN", "Lantern Helmet" },
    { "ENCHANTED_IRON_BLOCK", "Enchanted Iron Block" },
    { "ENCHANTED_JUNGLE_LOG", "Enchanted Jungle Wood" },
    { "ENCHANTED_HOPPER", "Enchanted Hopper" },
    { "ENCHANTED_LAPIS_LAZULI", "Enchanted Lapis Lazuli" },
    { "ENCHANTED_IRON", "Enchanted Iron" },
    { "ENCHANTED_LEATHER", "Enchanted Leather" },
    { "ENCHANTED_MELON", "Enchanted Melon" },
    { "ENCHANTED_MELON_BLOCK", "Enchanted Melon Block" },
    { "ENCHANTED_MUTTON", "Enchanted Mutton" },
    { "ENCHANTED_NETHER_STALK", "Enchanted Nether Wart" },
    { "ENCHANTED_MAGMA_CREAM", "Enchanted Magma Cream" },
    { "ENCHANTED_LAPIS_LAZULI_BLOCK", "Enchanted Lapis Block" },
    { "ENCHANTED_PACKED_ICE", "Enchanted Packed Ice" },
    { "ENCHANTED_PAPER", "Enchanted Paper" },
    { "ENCHANTED_EGG", "Enchanted Egg" },
    { "ENCHANTED_POPPY", "Enchanted Poppy" },
    { "ENCHANTED_POISONOUS_POTATO", "Enchanted Poisonous Potato" },
    { "ENCHANTED_POTATO", "Enchanted Potato" },
    { "ENCHANTED_PRISMARINE_CRYSTALS", "Enchanted Prismarine Crystals" },
    { "ENCHANTED_PRISMARINE_SHARD", "Enchanted Prismarine Shard" },
    { "ENCHANTED_PUFFERFISH", "Enchanted Pufferfish" },
    { "ENCHANTED_OAK_LOG", "Enchanted Oak Wood" },
    { "ENCHANTED_QUARTZ", "Enchanted Quartz" },
    { "ENCHANTED_PORK", "Enchanted Pork" },
    { "ENCHANTED_QUARTZ_BLOCK", "Enchanted Quartz Block" },
    { "ENCHANTED_OBSIDIAN", "Enchanted Obsidian" },
    { "ENCHANTED_RABBIT", "Enchanted Raw Rabbit" },
    { "ENCHANTED_RABBIT_HIDE", "Enchanted Rabbit Hide" },
    { "ENCHANTED_RABBIT_FOOT", "Enchanted Rabbit Foot" },
    { "ENCHANTED_RAW_FISH", "Enchanted Raw Fish" },
    { "ENCHANTED_RAW_SALMON", "Enchanted Raw Salmon" },
    { "ENCHANTED_PUMPKIN", "Enchanted Pumpkin" },
    { "ENCHANTED_RAW_BEEF", "Enchanted Raw Beef" },
    { "ENCHANTED_REDSTONE_LAMP", "Enchanted Redstone Lamp" },
    { "ENCHANTED_RED_MUSHROOM", "Enchanted Red Mushroom" },
    { "ENCHANTED_RAW_CHICKEN", "Enchanted Raw Chicken" },
    { "ENCHANTED_SAND", "Enchanted Sand" },
    { "ENCHANTED_SEEDS", "Enchanted Seeds" },
    { "ENCHANTED_ROTTEN_FLESH", "Enchanted Rotten Flesh" },
    { "ENCHANTED_SLIME_BALL", "Enchanted Slimeball" },
    { "ENCHANTED_SLIME_BLOCK", "Enchanted Slime Block" },
    { "ENCHANTED_REDSTONE", "Enchanted Redstone" },
    { "ENCHANTED_SPONGE", "Enchanted Sponge" },
    { "ENCHANTED_SPIDER_EYE", "Enchanted Spider Eye" },
    { "ENCHANTED_SNOW_BLOCK", "Enchanted Snow Block" },
    { "ENCHANTED_SPRUCE_LOG", "Enchanted Spruce Wood" },
    { "ENCHANTED_SUGAR", "Enchanted Sugar" },
    { "ENCHANTED_WATER_LILY", "Enchanted Lily Pad" },
    { "ENCHANTED_WET_SPONGE", "Enchanted Wet Sponge" },
    { "ENCHANTED_SUGAR_CANE", "Enchanted Sugar Cane" },
    { "ENCHANTED_LAVA_BUCKET", "Enchanted Lava Bucket" },
    { "ENCHANTED_STRING", "Enchanted String" },
    { "ENCHANTMENT_TABLE", "Enchantment Table" },
    { "ENCHANTED_WOOL", "Enchanted Wool" },
    { "ENCHANTING_PLUS", "Enchanting Table+" },
    { "ENDER_CHEST", "Ender Chest" },
    { "ENDER_ARTIFACT", "Ender Artifact" },
    { "ENDER_PLUS", "Ender Chest+" },
    { "ENDERMAN_MASK", "Enderman Mask" },
    { "ENCHANTED_REDSTONE_BLOCK", "Enchanted Redstone Block" },
    { "ENDSTONE_CHEST", "Endstone Chest+" },
    { "ENDER_PORTAL_FRAME", "End Portal Frame" },
    { "ENDER_STONE", "End Stone" },
    { "END_BIOME_STICK", "End Biome Stick" },
    { "ENDER_BOW", "Ender Bow" },
    { "ENDER_PEARL", "Ender Pearl" },
    { "END_CHESTPLATE", "Ender Chestplate" },
    { "END_LEGGINGS", "Ender Leggings" },
    { "ENDSTONE_ROSE", "Endstone Rose" },
    { "END_STONE_BOW", "End Stone Bow" },
    { "END_SWORD", "End Sword" },
    { "EXPLOSIVE_BOW", "Explosive Bow" },
    { "EXPLOSIVE_MINECART", "Minecart with TNT" },
    { "EXPERIENCE_ARTIFACT", "Experience Artifact" },
    { "END_STONE_SWORD", "End Stone Sword" },
    { "EYE_OF_ENDER", "Eye of Ender" },
    { "EXP_BOTTLE", "Experience Bottle" },
    { "END_BOOTS", "Ender Boots" },
    { "FAIRY_BOOTS", "Fairy's Galoshes" },
    { "FAIRY_CHESTPLATE", "Fairy's Polo" },
    { "FANCY_FLOWER_POT", "Flower Pot" },
    { "FANCY_TUXEDO_BOOTS", "Fancy Tuxedo Oxfords" },
    { "FANCY_TUXEDO_CHESTPLATE", "Fancy Tuxedo Jacket" },
    { "FANCY_TUXEDO_LEGGINGS", "Fancy Tuxedo Pants" },
    { "FAIRY_HELMET", "Fairy's Fedora" },
    { "FARMER_BOOTS", "Farmer Boots" },
    { "FAIRY_LEGGINGS", "Fairy's Trousers" },
    { "FARMING_1_PORTAL", "Portal to the Barn" },
    { "FARMER_ROD", "Farmer's Rod" },
    { "FARMING_2_PORTAL", "Portal to Mushroom Island" },
    { "FARMING_1_TRAVEL_SCROLL", "Travel Scroll to the Barn" },
    { "FARMING_2_TRAVEL_SCROLL", "Travel Scroll to Mushroom Island" },
    { "FANCY_SWORD", "Fancy Sword" },
    { "END_HELMET", "Ender Helmet" },
    { "FARMER_ORB", "Farmer Orb" },
    { "FARMING_ISLAND", "Farming Island" },
    { "FARM_ARMOR_BOOTS", "Farm Armor Boots" },
    { "FARM_ARMOR_HELMET", "Farm Armor Helmet" },
    { "FARM_ARMOR_CHESTPLATE", "Farm Armor Chestplate" },
    { "FARM_ARMOR_LEGGINGS", "Farm Armor Leggings" },
    { "FARM_SUIT_HELMET", "Farm Suit Helmet" },
    { "FARM_SUIT_BOOTS", "Farm Suit Boots" },
    { "FEATHER_ARTIFACT", "Feather Artifact" },
    { "FARM_SUIT_LEGGINGS", "Farm Suit Leggings" },
    { "FEATHER", "Feather" },
    { "FARM_SUIT_CHESTPLATE", "Farm Suit Chestplate" },
    { "FENCE_GATE", "Oak Fence Gate" },
    { "FENCE", "Oak Fence" },
    { "FIREBALL", "Fire Charge" },
    { "FERMENTED_SPIDER_EYE", "Fermented Spider Eye" },
    { "FIREWORK", "Firework Rocket" },
    { "FIREWORK_CHARGE", "Firework Star" },
    { "FIREPLACE", "Fireplace" },
    { "FARMING_TALISMAN", "Farming Talisman" },
    { "FISH_AFFINITY_TALISMAN", "Fish Affinity Talisman" },
    { "FISH_BAIT", "Fish Bait" },
    { "FISH_HAT", "Fish Hat" },
    { "FLAMING_SWORD", "Flaming Sword" },
    { "FISHING_ROD", "Fishing Rod" },
    { "FLINT_AND_STEEL", "Flint and Steel" },
    { "FLINT", "Flint" },
    { "FLOWER_POT_ITEM", "Flower Pot" },
    { "FLYCATCHER_UPGRADE", "Flycatcher" },
    { "FLYING_BATS", "Flying Bats" },
    { "FLINT_SHOVEL", "Flint Shovel" },
    { "FOOD_TROUGH", "Food Trough" },
    { "FORAGING_1_PORTAL", "Portal to Birch Park" },
    { "FEATHER_RING", "Feather Ring" },
    { "FORAGING_2_PORTAL", "Portal to Spruce Woods" },
    { "FORAGING_3_PORTAL", "Portal to Jungle Island" },
    { "FORAGING_4_PORTAL", "Portal to Savanna Woodland" },
    { "FORAGING_5_PORTAL", "Portal to Dark Thicket" },
    { "FLY_SWATTER", "Fly Swatter" },
    { "FOREST_BIOME_STICK", "Forest Biome Stick" },
    { "FRENCH_BREAD", "French Bread" },
    { "FROSTY_SNOW_BALL", "Frosty Snowball" },
    { "FORAGING_1_TRAVEL_SCROLL", "Travel Scroll to The Park" },
    { "FEATHER_TALISMAN", "Feather Talisman" },
    { "FOUL_FLESH", "Foul Flesh" },
    { "FROZEN_BLAZE_BOOTS", "Frozen Blaze Boots" },
    { "FROZEN_BLAZE_CHESTPLATE", "Frozen Blaze Chestplate" },
    { "FROZEN_SCYTHE", "Frozen Scythe" },
    { "FURNACE", "Furnace" },
    { "FROZEN_BLAZE_LEGGINGS", "Frozen Blaze Leggings" },
    { "GAME_BREAKER", "Game Breaker" },
    { "GARLAND", "Garland" },
    { "FURNACE_PLUS", "Furnace+" },
    { "FROZEN_BLAZE_HELMET", "Frozen Blaze Helmet" },
    { "GHOST_BOOK", "Ghost Book" },
    { "GHAST_HEAD", "Ghast Head" },
    { "GHAST_TEAR", "Ghast Tear" },
    { "GIFT_THE_FISH", "Gift the Fish" },
    { "GIFT_COMPASS", "Gift Compass" },
    { "GLASS", "Glass" },
    { "FROZEN_CHICKEN", "Frozen Chicken" },
    { "GLOWSTONE_DUST", "Glowstone Dust" },
    { "GLASS_BOTTLE", "Glass Bottle" },
    { "GINGERBREAD_PERSONALITY", "Gingerbread Man Minion Skin" },
    { "GOLDEN_CARROT", "Golden Carrot" },
    { "GOLDEN_APPLE", "Golden Apple" },
    { "GOLDEN_TOOTH", "Golden Tooth" },
    { "GLOWSTONE", "Glowstone" },
    { "GOLD_BARDING", "Gold Horse Armor" },
    { "GOLD_BLOCK", "Block of Gold" },
    { "GOLD_BOOTS", "Golden Boots" },
    { "GOLDEN_APPLE:1", "Enchanted Golden Apple" },
    { "GOLD_CHEST", "Gold Chest+" },
    { "GOLD_CANDY", "Golden Treat" },
    { "GOLD_CHESTPLATE", "Golden Chestplate" },
    { "GOLD_HELMET", "Golden Helmet" },
    { "GOLD_HOE", "Golden Hoe" },
    { "GOLD_GIFT", "Golden Gift" },
    { "GOLD_LEGGINGS", "Golden Leggings" },
    { "GOLDEN_POWDER", "Golden Powder" },
    { "FIRE_TALISMAN", "Fire Talisman" },
    { "GOLD_ORE", "Gold Ore" },
    { "GOLD_PLATE", "Light Weighted Pressure Plate" },
    { "GOLD_INGOT", "Gold Ingot" },
    { "GOLD_PICKAXE", "Golden Pickaxe" },
    { "GOLD_NUGGET", "Gold Nugget" },
    { "GOLD_SPADE", "Golden Shovel" },
    { "GOLD_SWORD", "Golden Sword" },
    { "GOLEM_ARMOR_BOOTS", "Golem Armor Boots" },
    { "GOLEM_ARMOR_HELMET", "Golem Armor Helmet" },
    { "GOLEM_ARMOR_LEGGINGS", "Golem Armor Leggings" },
    { "GRANDFATHER_CLOCK", "Grandfather Clock" },
    { "GOLD_RECORD", "Music Disc - 13" },
    { "GRAND_EXP_BOTTLE", "Grand Experience Bottle" },
    { "GRASS", "Grass" },
    { "GRAVEL", "Gravel" },
    { "GRAPPLING_HOOK", "Grappling Hook" },
    { "GRAVITY_TALISMAN", "Gravity Talisman" },
    { "GOLEM_SWORD", "Golem Sword" },
    { "GREAT_CARROT_CANDY", "Great Carrot Candy" },
    { "GREATER_BACKPACK", "Greater Backpack" },
    { "GREEN_RECORD", "Music Disc - Cat" },
    { "GREEN_GIFT", "Green Gift" },
    { "GRILLED_PORK", "Cooked Porkchop" },
    { "GOLEM_ARMOR_CHESTPLATE", "Golem Armor Chestplate" },
    { "GRIZZLY_BAIT", "Grizzly Bait" },
    { "GROWTH_CHESTPLATE", "Chestplate of Growth" },
    { "GROWTH_HELMET", "Helmet of Growth" },
    { "GRINCH_PERSONALITY", "Grinch Minion Skin" },
    { "GROWTH_BOOTS", "Boots of Growth" },
    { "HALLOWEEN_CANDLES", "Halloween Candles" },
    { "GROWTH_LEGGINGS", "Leggings of Growth" },
    { "GREEN_CANDY", "Green Candy" },
    { "GOLD_AXE", "Golden Axe" },
    { "HAMSTER_WHEEL", "Hamster Wheel" },
    { "GUARDIAN_CHESTPLATE", "Guardian Chestplate" },
    { "HARD_CLAY", "Hardened Clay" },
    { "HARD_GLASS", "Hard Glass" },
    { "HARP", "Personal Harp" },
    { "HASTE_BLOCK", "Haste Block" },
    { "HARDENED_DIAMOND_CHESTPLATE", "Hardened Diamond Chestplate" },
    { "HAY_BED", "Hay Bed" },
    { "HAY_BLOCK", "Hay Bale" },
    { "HEALING_RING", "Healing Ring" },
    { "HARDENED_DIAMOND_BOOTS", "Hardened Diamond Boots" },
    { "HARDENED_DIAMOND_LEGGINGS", "Hardened Diamond Leggings" },
    { "HARDENED_DIAMOND_HELMET", "Hardened Diamond Helmet" },
    { "HELMET_OF_THE_PACK", "Helmet of the Pack" },
    { "HOPPER_MINECART", "Minecart with Hopper" },
    { "HOPPER", "Hopper" },
    { "HORSEMAN_CANDLE", "Horseman's Candle" },
    { "HASTE_RING", "Haste Ring" },
    { "HILT_OF_TRUE_ICE", "Hilt of True Ice" },
    { "HUB_CRYPTS_TRAVEL_SCROLL", "Travel Scroll to Hub Crypts" },
    { "HUB_DA_TRAVEL_SCROLL", "Travel Scroll to Dark Auction" },
    { "HUGE_MUSHROOM_1", "Brown Mushroom Block" },
    { "HUGE_MUSHROOM_2", "Red Mushroom Block" },
    { "HUB_CASTLE_TRAVEL_SCROLL", "Travel Scroll to Hub Castle" },
    { "HEALING_TALISMAN", "Healing Talisman" },
    { "HUNTER_RING", "Hunter Ring" },
    { "HUNTER_TALISMAN", "Hunter Talisman" },
    { "HYPIXEL_CASTLE", "Hypixel Sandcastle" },
    { "HURRICANE_BOW", "Hurricane Bow" },
    { "HUNTER_KNIFE", "Hunter Knife" },
    { "HUB_PORTAL", "Portal to the Hub" },
    { "ICE_CREAM_PERSONALITY", "Ice Cream Minion Skin" },
    { "ICE_HUNK", "Hunk of Ice" },
    { "ICE_LOLLY_PERSONALITY", "Ice Lolly Minion Skin" },
    { "ILLUSION_GLASS", "Illusion Glass" },
    { "ICE", "Ice" },
    { "INK_SACK", "Ink Sack" },
    { "INK_SACK:10", "Lime Dye" },
    { "INK_SACK:11", "Dandelion Yellow" },
    { "ICE_BAIT", "Ice Bait" },
    { "INK_SACK:12", "Light Blue Dye" },
    { "INK_SACK:13", "Magenta Dye" },
    { "INK_SACK:14", "Orange Dye" },
    { "INK_SACK:2", "Cactus Green" },
    { "INK_SACK:3", "Cocoa Beans" },
    { "INK_SACK:1", "Rose Red" },
    { "INK_SACK:5", "Purple Dye" },
    { "INK_SACK:6", "Cyan Dye" },
    { "INK_SACK:7", "Light Gray Dye" },
    { "INK_SACK:8", "Gray Dye" },
    { "INK_SACK:9", "Pink Dye" },
    { "INK_SACK:15", "Bone Meal" },
    { "INK_SACK:4", "Lapis Lazuli" },
    { "INTIMIDATION_ARTIFACT", "Intimidation Artifact" },
    { "INK_WAND", "Ink Wand" },
    { "INTIMIDATION_RING", "Intimidation Ring" },
    { "IRON_BARDING", "Iron Horse Armor" },
    { "IRON_AXE", "Iron Axe" },
    { "IRON_BOOTS", "Iron Boots" },
    { "IRON_CHEST", "Iron Chest+" },
    { "ICE_ROD", "Ice Rod" },
    { "IRON_DOOR", "Iron Door" },
    { "IRON_FENCE", "Iron Bars" },
    { "IRON_BLOCK", "Block of Iron" },
    { "IRON_HOE", "Iron Hoe" },
    { "IRON_CHESTPLATE", "Iron Chestplate" },
    { "IRON_HELMET", "Iron Helmet" },
    { "IRON_LEGGINGS", "Iron Leggings" },
    { "IRON_ORE", "Iron Ore" },
    { "IRON_PLATE", "Heavy Weighted Pressure Plate" },
    { "INTIMIDATION_TALISMAN", "Intimidation Talisman" },
    { "IRON_INGOT", "Iron Ingot" },
    { "IRON_TRAPDOOR", "Iron Trapdoor" },
    { "IRON_SPADE", "Iron Shovel" },
    { "JACK_O_LANTERN", "Jack o' Lantern" },
    { "ITEM_FRAME", "Item Frame" },
    { "JUKEBOX", "Jukebox" },
    { "JINGLE_BELLS", "Jingle Bells" },
    { "JUNGLE_BIOME_STICK", "Jungle Biome Stick" },
    { "JUNGLE_DOOR_ITEM", "Jungle Door" },
    { "JUNGLE_FENCE", "Jungle Fence" },
    { "JUNGLE_FENCE_GATE", "Jungle Fence Gate" },
    { "JUNGLE_WOOD_STAIRS", "Jungle Wood Stairs" },
    { "KILLER_PERSONALITY", "Killer Minion Skin" },
    { "KNOCKOFF_COLA", "KnockOff��� Cola" },
    { "IRON_SWORD", "Iron Sword" },
    { "JUNGLE_AXE", "Jungle Axe" },
    { "LADDER", "Ladder" },
    { "LADY_BUG_PERSONALITY", "Lady Bug Minion Skin" },
    { "KRAMPUS_HELMET", "Krampus Helmet" },
    { "LAPIS_ARMOR_BOOTS", "Lapis Armor Boots" },
    { "LAPIS_ARMOR_LEGGINGS", "Lapis Armor Leggings" },
    { "IRON_PICKAXE", "Iron Pickaxe" },
    { "LAPIS_CHEST", "Lapis Chest+" },
    { "LAPIS_ORE", "Lapis Lazuli Ore" },
    { "LAPIS_BLOCK", "Lapis Lazuli Block" },
    { "LARGE_BED", "Large Bed" },
    { "LAPIS_ARMOR_CHESTPLATE", "Lapis Armor Chestplate" },
    { "LAUNCH_PAD", "Launch Pad" },
    { "LARGE_BACKPACK", "Large Backpack" },
    { "LAPIS_ARMOR_HELMET", "Lapis Armor Helmet" },
    { "LAVA_BUCKET", "Lava Bucket" },
    { "LAVA_TALISMAN", "Lava Talisman" },
    { "LEAFLET_BOOTS", "Leaflet Sandals" },
    { "LEAFLET_HELMET", "Leaflet Hat" },
    { "LEAFLET_CHESTPLATE", "Leaflet Tunic" },
    { "LARGE_ENCHANTED_CHEST", "Large Storage" },
    { "LEAFLET_LEGGINGS", "Leaflet Pants" },
    { "LEASH", "Lead" },
    { "LEATHER_BOOTS", "Leather Boots" },
    { "LEATHER_HELMET", "Leather Helmet" },
    { "LEATHER_CHESTPLATE", "Leather Chestplate" },
    { "LEATHER", "Leather" },
    { "LEAVES:1", "Spruce Leaves" },
    { "LEATHER_LEGGINGS", "Leather Leggings" },
    { "LEAVES:2", "Birch Leaves" },
    { "LEAVES_2", "Acacia Leaves" },
    { "LEAVES:3", "Jungle Leaves" },
    { "LEAVES", "Oak Leaves" },
    { "LEGGINGS_OF_THE_PACK", "Leggings of the Pack" },
    { "LEVER", "Lever" },
    { "LEAVES_2:1", "Dark Oak Leaves" },
    { "LIGHT_BAIT", "Light Bait" },
    { "LOG:0", "Oak Wood" },
    { "LOG:1", "Spruce Wood" },
    { "LOG:2", "Birch Wood" },
    { "LOG:3", "Jungle Wood" },
    { "LOG_2", "Acacia Wood" },
    { "LEGEND_ROD", "Rod of Legends" },
    { "LONG_GRASS:1", "Long Grass" },
    { "LONG_GRASS:2", "Fern" },
    { "LOG_2:1", "Dark Oak Wood" },
    { "LOG", "Oak Wood" },
    { "MAGMA_BOW", "Magma Bow" },
    { "MAGMA_CREAM", "Magma Cream" },
    { "MAGIC_MUSHROOM_SOUP", "Magical Mushroom Soup" },
    { "MAGMA_CUBE_HEAD", "Magma Cube Head" },
    { "MANA_FLUX_POWER_ORB", "Mana Flux Power Orb" },
    { "MAP", "Map" },
    { "MAP:-14", "Map" },
    { "MAP:-74", "Map" },
    { "MASTIFF_BOOTS", "Mastiff Boots" },
    { "MAGNETIC_TALISMAN", "Magnetic Talisman" },
    { "MASTIFF_HELMET", "Mastiff Crown" },
    { "MASTIFF_CHESTPLATE", "Mastiff Chestplate" },
    { "MEDIUM_BACKPACK", "Medium Backpack" },
    { "MEDIUM_ENCHANTED_CHEST", "Medium Storage" },
    { "MELON_BLOCK", "Melon" },
    { "MELON", "Melon" },
    { "MELON_SEEDS", "Melon Seeds" },
    { "MELON_PERSONALITY", "Melon Minion Skin" },
    { "MAGICAL_WATER_BUCKET", "Magical Water Bucket" },
    { "MILK_BUCKET", "Milk Bucket" },
    { "MINECART", "Minecart" },
    { "LEAPING_SWORD", "Leaping Sword" },
    { "MASTIFF_LEGGINGS", "Mastiff Leggings" },
    { "MINER_OUTFIT_HELMET", "Miner's Outfit Helmet" },
    { "MINER_OUTFIT_BOOTS", "Miner's Outfit Boots" },
    { "MINING_1_PORTAL", "Portal to the Gold Mine" },
    { "MINING_1_TRAVEL_SCROLL", "Travel Scroll to the Gold Mine" },
    { "MINING_2_PORTAL", "Portal to the Deep Caverns" },
    { "MINER_OUTFIT_CHESTPLATE", "Miner's Outfit Chestplate" },
    { "MINER_OUTFIT_LEGGINGS", "Miner's Outfit Leggings" },
    { "MINION_CHAIR", "Minion Chair" },
    { "MIDAS_SWORD", "Midas' Sword" },
    { "MINNOW_BAIT", "Minnow Bait" },
    { "MINE_TALISMAN", "Mine Affinity Talisman" },
    { "MOSSY_COBBLESTONE", "Moss Stone" },
    { "MINING_2_TRAVEL_SCROLL", "Travel Scroll to Deep Caverns" },
    { "MONSTER_EGG", "Spawn Egg" },
    { "MOSQUITO_BOW", "Mosquito Bow" },
    { "MUSHROOM_BOOTS", "Mushroom Boots" },
    { "MUSHROOM_SOUP", "Mushroom Soup" },
    { "MUSHROOM_HELMET", "Mushroom Helmet" },
    { "MUTTON", "Mutton" },
    { "MUSHROOM_CHESTPLATE", "Mushroom Chestplate" },
    { "NAME_TAG", "Name Tag" },
    { "MUSHROOM_LEGGINGS", "Mushroom Leggings" },
    { "MYCEL", "Mycelium" },
    { "NETHERRACK", "Netherrack" },
    { "NETHER_BRICK", "Nether Bricks" },
    { "NETHER_BRICK_STAIRS", "Nether Bricks Stairs" },
    { "NETHER_FENCE", "Nether Brick Fence" },
    { "NETHER_BRICK_ITEM", "Nether Brick" },
    { "NETHER_BIOME_STICK", "Nether Biome Stick" },
    { "NETHER_FORTRESS_BOSS_TRAVEL_SCROLL", "Travel Scroll to Magma Fields" },
    { "NEW_YEAR_CAKE", "New Year Cake" },
    { "NEW_YEAR_CAKE_BAG", "New Year Cake Bag" },
    { "NETHER_STALK", "Nether Wart" },
    { "NIGHT_SAVER", "Night Saver" },
    { "NOPE_THE_FISH", "Nope the Fish" },
    { "NOTE_BLOCK", "Noteblock" },
    { "MUSIC_PANTS", "Stereo Pants" },
    { "MINION_EXPANDER", "Minion Expander" },
    { "NUTCRACKER", "Nutcracker" },
    { "OBSIDIAN_CHESTPLATE", "Obsidian Chestplate" },
    { "NETHER_WART_ISLAND", "Nether Wart Island" },
    { "NIGHT_VISION_CHARM", "Night Vision Charm" },
    { "OLD_DRAGON_BOOTS", "Old Dragon Boots" },
    { "OLD_DRAGON_HELMET", "Old Dragon Helmet" },
    { "OLD_DRAGON_LEGGINGS", "Old Dragon Leggings" },
    { "ORNATE_ZOMBIE_SWORD", "Ornate Zombie Sword" },
    { "OBSIDIAN", "Obsidian" },
    { "OVERFLUX_CAPACITOR", "Overflux Capacitor" },
    { "OVERFLUX_POWER_ORB", "Overflux Power Orb" },
    { "PAINTING", "Painting" },
    { "PACKED_ICE", "Packed Ice" },
    { "OLD_DRAGON_CHESTPLATE", "Old Dragon Chestplate" },
    { "PEDESTAL", "X PEDESTAL" },
    { "PARK_JUNGLE_TRAVEL_SCROLL", "Travel Scroll to Jungle Island" },
    { "PERFECT_BOOTS_10", "Perfect Boots - Tier X" },
    { "PERFECT_BOOTS_11", "Perfect Boots - Tier XI" },
    { "PERFECT_BOOTS_12", "Perfect Boots - Tier XII" },
    { "PAPER", "Paper" },
    { "PERFECT_BOOTS_1", "Perfect Boots - Tier I" },
    { "PERFECT_BOOTS_3", "Perfect Boots - Tier III" },
    { "PERFECT_BOOTS_5", "Perfect Boots - Tier V" },
    { "PERFECT_BOOTS_6", "Perfect Boots - Tier VI" },
    { "PERFECT_BOOTS_7", "Perfect Boots - Tier VII" },
    { "PERFECT_BOOTS_2", "Perfect Boots - Tier II" },
    { "PERFECT_BOOTS_9", "Perfect Boots - Tier IX" },
    { "PERFECT_BOOTS_8", "Perfect Boots - Tier VIII" },
    { "PERFECT_BOOTS_4", "Perfect Boots - Tier IV" },
    { "PERFECT_CHESTPLATE_10", "Perfect Chestplate - Tier X" },
    { "PERFECT_CHESTPLATE_2", "Perfect Chestplate - Tier II" },
    { "PERFECT_CHESTPLATE_3", "Perfect Chestplate - Tier III" },
    { "PERFECT_CHESTPLATE_4", "Perfect Chestplate - Tier IV" },
    { "PERFECT_CHESTPLATE_5", "Perfect Chestplate - Tier V" },
    { "PERFECT_CHESTPLATE_6", "Perfect Chestplate - Tier VI" },
    { "PERFECT_CHESTPLATE_7", "Perfect Chestplate - Tier VII" },
    { "PERFECT_CHESTPLATE_8", "Perfect Chestplate - Tier VIII" },
    { "PERFECT_CHESTPLATE_9", "Perfect Chestplate - Tier IX" },
    { "PARK_CAVE_TRAVEL_SCROLL", "Travel Scroll to Howling Cave" },
    { "PERFECT_HELMET_10", "Perfect Helmet - Tier X" },
    { "PERFECT_CHESTPLATE_1", "Perfect Chestplate - Tier I" },
    { "PERFECT_HELMET_11", "Perfect Helmet - Tier XI" },
    { "PERFECT_HELMET_2", "Perfect Helmet - Tier II" },
    { "PERFECT_HELMET_3", "Perfect Helmet - Tier III" },
    { "PERFECT_HELMET_4", "Perfect Helmet - Tier IV" },
    { "PERFECT_HELMET_5", "Perfect Helmet - Tier V" },
    { "PERFECT_HELMET_6", "Perfect Helmet - Tier VI" },
    { "PERFECT_HELMET_7", "Perfect Helmet - Tier VII" },
    { "PERFECT_HELMET_8", "Perfect Helmet - Tier VIII" },
    { "PERFECT_HELMET_9", "Perfect Helmet - Tier IX" },
    { "PERFECT_HELMET_1", "Perfect Helmet - Tier I" },
    { "PERFECT_LEGGINGS_10", "Perfect Leggings - Tier X" },
    { "PERFECT_LEGGINGS_11", "Perfect Leggings - Tier XI" },
    { "PERFECT_LEGGINGS_1", "Perfect Leggings - Tier I" },
    { "PERFECT_LEGGINGS_2", "Perfect Leggings - Tier II" },
    { "PERFECT_LEGGINGS_3", "Perfect Leggings - Tier III" },
    { "PERFECT_LEGGINGS_4", "Perfect Leggings - Tier IV" },
    { "PERFECT_LEGGINGS_5", "Perfect Leggings - Tier V" },
    { "PERFECT_LEGGINGS_7", "Perfect Leggings - Tier VII" },
    { "PERFECT_LEGGINGS_8", "Perfect Leggings - Tier VIII" },
    { "PERFECT_LEGGINGS_9", "Perfect Leggings - Tier IX" },
    { "PERFECT_CHESTPLATE_12", "Perfect Chestplate - Tier XII" },
    { "PET", "[Lvl 56] Rock" },
    { "PERFECT_HELMET_12", "Perfect Helmet - Tier XII" },
    { "PET_ITEM_BIG_TEETH_COMMON", "Big Teeth" },
    { "PERFECT_LEGGINGS_12", "Perfect Leggings - Tier XII" },
    { "PET_ITEM_BUBBLEGUM", "Bubblegum" },
    { "PET_ITEM_ALL_SKILLS_BOOST_COMMON", "All Skills Exp Boost" },
    { "PET_ITEM_COMBAT_SKILL_BOOST_RARE", "Combat Exp Boost" },
    { "PET_ITEM_COMBAT_SKILL_BOOST_COMMON", "Combat Exp Boost" },
    { "PET_ITEM_COMBAT_SKILL_BOOST_EPIC", "Combat Exp Boost" },
    { "PERSONAL_BANK_ITEM", "Personal Bank Item" },
    { "PET_ITEM_FARMING_SKILL_BOOST_COMMON", "Farming Exp Boost" },
    { "PET_ITEM_FARMING_SKILL_BOOST_RARE", "Farming Exp Boost" },
    { "PET_ITEM_FISHING_SKILL_BOOST_COMMON", "Fishing Exp Boost" },
    { "PET_ITEM_EXP_SHARE_DROP", "Exp Share Core" },
    { "PET_ITEM_FISHING_SKILL_BOOST_EPIC", "Fishing Exp Boost" },
    { "PET_ITEM_EXP_SHARE", "Exp Share" },
    { "PET_ITEM_COMBAT_SKILL_BOOST_UNCOMMON", "Combat Exp Boost" },
    { "OLD_FRAGMENT", "Old Dragon Fragment" },
    { "PET_ITEM_FISHING_SKILL_BOOST_RARE", "Fishing Exp Boost" },
    { "PET_ITEM_FORAGING_SKILL_BOOST_EPIC", "Foraging Exp Boost" },
    { "PET_ITEM_HARDENED_SCALES_UNCOMMON", "Hardened Scales" },
    { "PET_ITEM_FORAGING_SKILL_BOOST_COMMON", "Foraging Exp Boost" },
    { "PET_ITEM_MINING_SKILL_BOOST_COMMON", "Mining Exp Boost" },
    { "PET_ITEM_MINING_SKILL_BOOST_RARE", "Mining Exp Boost" },
    { "PET_ITEM_LUCKY_CLOVER", "Lucky Clover" },
    { "PET_ITEM_SHARPENED_CLAWS_UNCOMMON", "Sharpened Claws" },
    { "PET_ITEM_IRON_CLAWS_COMMON", "Iron Claws" },
    { "PET_ITEM_SADDLE", "Saddle" },
    { "PET_ITEM_FISHING_SKILL_BOOST_UNCOMMON", "Fishing Exp Boost" },
    { "PICNIC_SET", "Picnic Set" },
    { "PET_ITEM_TIER_BOOST_DROP", "Tier Boost Core" },
    { "PET_ITEM_TIER_BOOST", "Tier Boost" },
    { "PET_ITEM_LUCKY_CLOVER_DROP", "Lucky Clover Core" },
    { "PISTON_BASE", "Piston" },
    { "PISTON_STICKY_BASE", "Sticky Piston" },
    { "PET_ITEM_TEXTBOOK", "Textbook" },
    { "PLUMBER_SPONGE", "Plumber's Sponge" },
    { "PIGGY_BANK", "Piggy Bank" },
    { "POISONOUS_POTATO", "Poisonous Potato" },
    { "PIGMAN_SWORD", "Pigman Sword" },
    { "POLISHED_PEBBLE", "Polished Pebble" },
    { "PORK", "Raw Porkchop" },
    { "PIGS_FOOT", "Pig's Foot" },
    { "POND_ISLAND", "Pond Island" },
    { "POWERED_MINECART", "Minecart with Furnace" },
    { "POWERED_RAIL", "Powered Rail" },
    { "POOCH_SWORD", "Pooch Sword" },
    { "POTATO_ITEM", "Potato" },
    { "PRISMARINE", "Prismarine" },
    { "PRISMARINE:2", "Dark Prismarine" },
    { "PRISMARINE:1", "Prismarine Bricks" },
    { "PRISMARINE_BOW", "Prismarine Bow" },
    { "PRESENTS", "Present Stack" },
    { "PRISMARINE_CRYSTALS", "Prismarine Crystals" },
    { "PRISMARINE_SHARD", "Prismarine Shard" },
    { "PRISMARINE_BLADE", "Prismarine Blade" },
    { "PRISMARINE_ROD", "Prismarine Rod" },
    { "PROMISING_SPADE", "Promising Shovel" },
    { "PROMISING_AXE", "Promising Axe" },
    { "PROMISING_PICKAXE", "Promising Pickaxe" },
    { "POTION", "Critical IV Potion" },
    { "POTION_AFFINITY_TALISMAN", "Potion Affinity Talisman" },
    { "PROTECTOR_DRAGON_LEGGINGS", "Protector Dragon Leggings" },
    { "PUFFERFISH_HAT", "Pufferfish Hat" },
    { "PULPOUS_ORANGE_JUICE", "Pulpous Orange Juice" },
    { "PUMPKIN", "Pumpkin" },
    { "PUMPKIN_BOOTS", "Pumpkin Boots" },
    { "PUMPKIN_CHESTPLATE", "Pumpkin Chestplate" },
    { "PUMPKIN_HELMET", "Pumpkin Helmet" },
    { "PUMPKIN_LEGGINGS", "Pumpkin Leggings" },
    { "PUMPKIN_PIE", "Pumpkin Pie" },
    { "PUMPKIN_SEEDS", "Pumpkin Seeds" },
    { "PROTECTOR_DRAGON_CHESTPLATE", "Protector Dragon Chestplate" },
    { "QUARTZ", "Nether Quartz" },
    { "QUARTZ_BLOCK", "Block of Quartz" },
    { "QUARTZ_BLOCK:1", "Chiseled Quartz Block" },
    { "QUARTZ_BLOCK:2", "Pillar Quartz Block" },
    { "QUARTZ_ORE", "Nether Quartz Ore" },
    { "QUARTZ_STAIRS", "Quartz Stairs" },
    { "RABBIT", "Raw Rabbit" },
    { "PURPLE_CANDY", "Purple Candy" },
    { "RABBIT_FOOT", "Rabbit's Foot" },
    { "RABBIT_HIDE", "Rabbit Hide" },
    { "RADIANT_POWER_ORB", "Radiant Power Orb" },
    { "RABBIT_HAT", "Rabbit Hat" },
    { "RAILS", "Rail" },
    { "PROTECTOR_FRAGMENT", "Protector Dragon Fragment" },
    { "RAIDER_AXE", "Raider Axe" },
    { "PROTECTOR_DRAGON_HELMET", "Protector Dragon Helmet" },
    { "RAW_BEEF", "Raw Beef" },
    { "RAW_FISH:1", "Raw Salmon" },
    { "RAW_FISH:2", "Clownfish" },
    { "RAW_CHICKEN", "Raw Chicken" },
    { "RAW_FISH", "Raw Fish" },
    { "RAW_FISH:3", "Pufferfish" },
    { "REAPER_MASK", "Reaper Mask" },
    { "REAPER_SCYTHE", "Reaper Scythe" },
    { "RECORD_10", "Music Disc - Ward" },
    { "RECLUSE_FANG", "Recluse Fang" },
    { "RECORD_12", "Music Disc - Wait" },
    { "RECORD_11", "Music Disc - 11" },
    { "REAPER_SWORD", "Reaper Falchion" },
    { "PROTECTOR_DRAGON_BOOTS", "Protector Dragon Boots" },
    { "RECORD_3", "Music Disc - Blocks" },
    { "RECORD_5", "Music Disc - Far" },
    { "RECORD_4", "Music Disc - Chirp" },
    { "RECORD_6", "Music Disc - Mall" },
    { "RECORD_7", "Music Disc - Mellohi" },
    { "REDSTONE_CHEST", "Redstone Chest+" },
    { "REDSTONE_COMPARATOR", "Comparator" },
    { "REDSTONE_LAMP_OFF", "Redstone Lamp" },
    { "REDSTONE_ORE", "Redstone Ore" },
    { "REDSTONE_TORCH_ON", "Redstone Torch" },
    { "REDSTONE", "Redstone" },
    { "RECORD_9", "Music Disc - Strad" },
    { "RECORD_8", "Music Disc - Stal" },
    { "RED_CLAW_ARTIFACT", "Red Claw Artifact" },
    { "REDSTONE_BLOCK", "Block of Redstone" },
    { "RED_CLAW_RING", "Red Claw Ring" },
    { "RED_MUSHROOM", "Red Mushroom" },
    { "RED_GIFT", "Red Gift" },
    { "RED_ROSE:1", "Blue Orchid" },
    { "RED_ROSE:2", "Allium" },
    { "RED_ROSE:4", "Red Tulip" },
    { "RED_ROSE:3", "Azure Bluet" },
    { "RED_ROSE:5", "Orange Tulip" },
    { "RED_ROSE:6", "White Tulip" },
    { "RED_CLAW_EGG", "Red Claw Egg" },
    { "RED_SANDSTONE", "Red Sandstone" },
    { "RED_SANDSTONE:1", "Red Chiseled Sandstone" },
    { "RED_SANDSTONE:2", "Red Smooth Sandstone" },
    { "RED_ROSE:7", "Pink Tulip" },
    { "RED_TENT", "Red Tent" },
    { "RED_ROSE:8", "Oxeye Daisy" },
    { "RED_ROSE", "Poppy" },
    { "REVENANT_CATALYST", "Revenant Catalyst" },
    { "REVENANT_CHESTPLATE", "Revenant Chestplate" },
    { "REMNANT_OF_THE_EYE", "Remnant of the Eye" },
    { "REVENANT_LEGGINGS", "Revenant Leggings" },
    { "REVENANT_SWORD", "Revenant Falchion" },
    { "REVENANT_VISCERA", "Revenant Viscera" },
    { "RED_CLAW_TALISMAN", "Red Claw Talisman" },
    { "REVIVED_HEART", "Revived Heart" },
    { "REVENANT_BOOTS", "Revenant Boots" },
    { "REPELLING_CANDLE", "Repelling Candle" },
    { "ROOFED_FOREST_BIOME_STICK", "Roofed Forest Biome Stick" },
    { "ROOKIE_AXE", "Rookie Axe" },
    { "ROOKIE_HOE", "Rookie Hoe" },
    { "ROOKIE_PICKAXE", "Rookie Pickaxe" },
    { "ROOFED_FOREST_ISLAND", "Roofed Forest Island" },
    { "RUNAANS_BOW", "Runaan's Bow" },
    { "RUNE", "◆ Lightning Rune III" },
    { "SADDLE", "Saddle" },
    { "SALMON_HAT", "Salmon Hat" },
    { "SAND", "Sand" },
    { "SAND:1", "Red Sand" },
    { "SANDCASTLE_PERSONALITY", "Sandcastle Minion Skin" },
    { "SANDSTONE", "Sandstone" },
    { "SANDSTONE:1", "Chiseled Sandstone" },
    { "SANDSTONE:2", "Smooth Sandstone" },
    { "REVENANT_FLESH", "Revenant Flesh" },
    { "SAPLING", "Oak Sapling" },
    { "SAPLING:1", "Spruce Sapling" },
    { "SAPLING:2", "Birch Sapling" },
    { "SAPLING:3", "Jungle Sapling" },
    { "SAPLING:4", "Acacia Sapling" },
    { "RING_POTION_AFFINITY", "Potion Affinity Ring" },
    { "SAVANA_BIOME_STICK", "Savanna Biome Stick" },
    { "ROTTEN_FLESH", "Rotten Flesh" },
    { "SAPLING:5", "Dark Oak Sapling" },
    { "ROGUE_SWORD", "Rogue Sword" },
    { "SCARECROW", "Scarecrow" },
    { "SANTA_PERSONALITY", "Santa Minion Skin" },
    { "SCULPTORS_AXE", "Sculptor's Axe" },
    { "SCORPION_BOW", "Scorpion Bow" },
    { "SCAVENGER_TALISMAN", "Scavenger Talisman" },
    { "SEAL_OF_THE_FAMILY", "Seal of the Family" },
    { "SCORPION_FOIL", "Thick Scorpion Foil" },
    { "SEA_CREATURE_RING", "Sea Creature Ring" },
    { "SCYTHE_BLADE", "Scythe Blade" },
    { "SAVANA_BOW", "Savanna Bow" },
    { "SHADY_RING", "Shady Ring" },
    { "SHAMAN_SWORD", "Shaman Sword" },
    { "SEA_LANTERN", "Sea Lantern" },
    { "SHRIMP_THE_FISH", "Shrimp the Fish" },
    { "SHEARS", "Shears" },
    { "SILENCE_BLOCK", "Silence Block" },
    { "SIGN", "Sign" },
    { "SEEDS", "Seeds" },
    { "SEA_CREATURE_TALISMAN", "Sea Creature Talisman" },
    { "SEA_CREATURE_ARTIFACT", "Sea Creature Artifact" },
    { "SILENT_PEARL", "Silent Pearl" },
    { "SILK_EDGE_SWORD", "Silk-Edge Sword" },
    { "SILVER_FANG", "Silver Fang" },
    { "SILKY_LICHEN", "Silky Lichen" },
    { "SKELETON_HAT", "Skeleton Hat" },
    { "SKULL_CHEST", "Skull Chest++" },
    { "SKULL_ITEM", "Skeleton Skull" },
    { "SKULL_PERSONALITY", "Skull Minion Skin" },
    { "SKYBLOCK_BENCH", "Dark Oak Bench" },
    { "SKYBLOCK_CHAIR", "Dark Oak Chair" },
    { "SKYBLOCK_TABLE", "Dark Oak Table" },
    { "SLAYER_ENERGY_DRINK", "Slayer�� Energy Drink" },
    { "SKELETON_TALISMAN", "Skeleton Talisman" },
    { "SIMPLE_CARROT_CANDY", "Simple Carrot Candy" },
    { "SLIME_BLOCK", "Slime Block" },
    { "SLIME_BOW", "Slime Bow" },
    { "SLEEPING_EYE", "Sleeping Eye" },
    { "SLIME_BALL", "Slimeball" },
    { "SKELETON_HELMET", "Skeleton's Helmet" },
    { "SMALL_SHELVES", "Small Shelves" },
    { "SMALL_XTREE", "Small Holiday Tree" },
    { "SMOOTH_BRICK", "Stone Bricks" },
    { "SMOOTH_BRICK:1", "Mossy Stone Bricks" },
    { "SMOOTH_BRICK:2", "Cracked Stone Bricks" },
    { "SMOOTH_BRICK:3", "Chiseled Stone Bricks" },
    { "SMOOTH_STAIRS", "Stone Brick Stairs" },
    { "SMALL_BACKPACK", "Small Backpack" },
    { "SNOW", "Snow" },
    { "SNOWMAN", "Derpy Snowman" },
    { "SNOWFLAKE_THE_FISH", "Flake the Fish" },
    { "SMALL_ENCHANTED_CHEST", "Small Storage" },
    { "SNOW_BALL", "Snowball" },
    { "SNOW_BLASTER", "Frosty the Snow Blaster" },
    { "SLIME_HAT", "Slime Hat" },
    { "SNOW_SUIT_CHESTPLATE", "Snow Suit Chestplate" },
    { "SNOW_SUIT_HELMET", "Snow Suit Helmet" },
    { "SNOW_SUIT_LEGGINGS", "Snow Suit Leggings" },
    { "SNOW_BLOCK", "Snow Block" },
    { "SPECKLED_MELON", "Glistering Melon" },
    { "SNOW_SUIT_BOOTS", "Snow Suit Boots" },
    { "SPEEDSTER_CHESTPLATE", "Speedster Chestplate" },
    { "SPEEDSTER_BOOTS", "Speedster Boots" },
    { "SPEEDSTER_HELMET", "Speedster Helmet" },
    { "SPEEDSTER_LEGGINGS", "Speedster Leggings" },
    { "SPEED_ARTIFACT", "Speed Artifact" },
    { "SOLAR_PANEL", "Solar Panel" },
    { "SNOW_CANNON", "Frosty the Snow Cannon" },
    { "SPEED_RING", "Speed Ring" },
    { "SPEEDSTER_ROD", "Speedster Rod" },
    { "SPIDER_ARTIFACT", "Spider Artifact" },
    { "SPIDERS_DEN_TOP_TRAVEL_SCROLL", "Travel Scroll to Spider's Den Top of Nest" },
    { "SPIDER_BOOTS", "Spider's Boots" },
    { "SPIDER_EYE", "Spider Eye" },
    { "SPIDER_RING", "Spider Ring" },
    { "SPEED_TALISMAN", "Speed Talisman" },
    { "SPIDER_HAT", "Spider Hat" },
    { "SPIDER_TALISMAN", "Spider Talisman" },
    { "SPIRIT_MASK", "Spirit Mask" },
    { "SPIDER_SWORD", "Spider Sword" },
    { "SPIDER_CATALYST", "Spider Catalyst" },
    { "SPONGE_BOOTS", "Spongy Shoes" },
    { "SPONGE_CHESTPLATE", "Sponge Chestplate" },
    { "SPONGE_HELMET", "Sponge Helmet" },
    { "SPONGE_LEGGINGS", "Sponge Leggings" },
    { "SPONGE:1", "Wet Sponge" },
    { "SPOOKY_BAIT", "Spooky Bait" },
    { "SPONGE_ROD", "Sponge Rod" },
    { "SPONGE", "Sponge" },
    { "SPIKED_BAIT", "Spiked Bait" },
    { "SPOOKY_CHESTPLATE", "Spooky Chestplate" },
    { "SPOOKY_BOOTS", "Spooky Boots" },
    { "SPOOKY_DISC", "Spooky Disc" },
    { "SPOOKY_PIE", "Spooky Pie" },
    { "SPOOKY_LEGGINGS", "Spooky Leggings" },
    { "SPRUCE_DOOR_ITEM", "Spruce Door" },
    { "SPRUCE_FENCE", "Spruce Fence" },
    { "SPRUCE_FENCE_GATE", "Spruce Fence Gate" },
    { "SPRUCE_WOOD_STAIRS", "Spruce Wood Stairs" },
    { "SOUL_SAND", "Soul Sand" },
    { "SPOOKY_SHARD", "Spooky Shard" },
    { "SPOOKY_HELMET", "Spooky Helmet" },
    { "STAINED_CLAY", "White Hardened Clay" },
    { "STAINED_CLAY:1", "Orange Hardened Clay" },
    { "SPRAY_CAN", "Spray Can" },
    { "STAINED_CLAY:11", "Blue Hardened Clay" },
    { "STAINED_CLAY:12", "Brown Hardened Clay" },
    { "STACKED_PUMPKINS", "Stacked Pumpkins" },
    { "STAINED_CLAY:14", "Red Hardened Clay" },
    { "STAINED_CLAY:15", "Black Hardened Clay" },
    { "STAINED_CLAY:10", "Purple Hardened Clay" },
    { "STAINED_CLAY:2", "Magenta Hardened Clay" },
    { "STAINED_CLAY:4", "Yellow Hardened Clay" },
    { "STAINED_CLAY:5", "Lime Hardened Clay" },
    { "STAINED_CLAY:3", "Light Blue Hardened Clay" },
    { "STAINED_CLAY:6", "Pink Hardened Clay" },
    { "STAINED_CLAY:13", "Green Hardened Clay" },
    { "STAINED_CLAY:8", "Light Gray Hardened Clay" },
    { "STAINED_CLAY:7", "Gray Hardened Clay" },
    { "STAINED_GLASS:1", "Orange Stained Glass" },
    { "STAINED_GLASS:10", "Purple Stained Glass" },
    { "STAINED_GLASS:11", "Blue Stained Glass" },
    { "STAINED_GLASS", "White Stained Glass" },
    { "STAINED_GLASS:13", "Green Stained Glass" },
    { "STAINED_GLASS:14", "Red Stained Glass" },
    { "STAINED_GLASS:15", "Black Stained Glass" },
    { "STAINED_GLASS:2", "Magenta Stained Glass" },
    { "STAINED_GLASS:12", "Brown Stained Glass" },
    { "STAINED_GLASS:4", "Yellow Stained Glass" },
    { "STAINED_GLASS:5", "Lime Stained Glass" },
    { "STAINED_GLASS:3", "Light Blue Stained Glass" },
    { "STAINED_GLASS:7", "Gray Stained Glass" },
    { "STAINED_GLASS:6", "Pink Stained Glass" },
    { "STAINED_GLASS:8", "Light Gray Stained Glass" },
    { "SQUID_HAT", "Squid Hat" },
    { "STAINED_GLASS_PANE", "White Stained Glass Pane" },
    { "STAINED_GLASS_PANE:10", "Purple Stained Glass Pane" },
    { "STAINED_GLASS_PANE:11", "Blue Stained Glass Pane" },
    { "STAINED_GLASS_PANE:13", "Green Stained Glass Pane" },
    { "STAINED_GLASS_PANE:1", "Orange Stained Glass Pane" },
    { "STAINED_CLAY:9", "Cyan Hardened Clay" },
    { "STAINED_GLASS_PANE:2", "Magenta Stained Glass Pane" },
    { "STAINED_GLASS_PANE:14", "Red Stained Glass Pane" },
    { "STAINED_GLASS_PANE:3", "Light Blue Stained Glass Pane" },
    { "STAINED_GLASS_PANE:4", "Yellow Stained Glass Pane" },
    { "STAINED_GLASS_PANE:5", "Lime Stained Glass Pane" },
    { "STAINED_GLASS_PANE:6", "Pink Stained Glass Pane" },
    { "STAINED_GLASS_PANE:7", "Gray Stained Glass Pane" },
    { "STAINED_GLASS_PANE:15", "Black Stained Glass Pane" },
    { "STEP:1", "Sandstone Slab" },
    { "STEP:2", "Wooden Slab" },
    { "STEP", "Stone Slab" },
    { "STAINED_GLASS_PANE:8", "Light Gray Stained Glass Pane" },
    { "STEP:6", "Nether Brick Slab" },
    { "STEP:7", "Quartz Slab" },
    { "STEP:3", "Cobblestone Slab" },
    { "STICK", "Stick" },
    { "STOCKING", "Stocking" },
    { "STEP:5", "Stone Brick Slab" },
    { "STONE:1", "Granite" },
    { "STONE:2", "Polished Granite" },
    { "STONE:3", "Diorite" },
    { "STONE:4", "Polished Diorite" },
    { "STONE:5", "Andesite" },
    { "STONE:6", "Polished Andesite" },
    { "STOCK_OF_STONKS", "Stock of Stonks" },
    { "STONE_AXE", "Stone Axe" },
    { "STONE_BUTTON", "Stone Button" },
    { "STONE_BRIDGE", "Stone Platform" },
    { "STONE_HOE", "Stone Hoe" },
    { "STONE_PLATE", "Stone Pressure Plate" },
    { "STONE_SLAB2", "Red Sandstone Slab" },
    { "STONE_SPADE", "Stone Shovel" },
    { "STONE_PICKAXE", "Stone Pickaxe" },
    { "STONE_SWORD", "Stone Sword" },
    { "STOOL", "Stool" },
    { "STORAGE_MINECART", "Minecart with Chest" },
    { "STONE", "Stone" },
    { "STAINED_GLASS_PANE:12", "Brown Stained Glass Pane" },
    { "STONK_PICKAXE", "Stonk" },
    { "STRONG_DRAGON_HELMET", "Strong Dragon Helmet" },
    { "STRONG_DRAGON_BOOTS", "Strong Dragon Boots" },
    { "STRONG_DRAGON_CHESTPLATE", "Strong Dragon Chestplate" },
    { "SUGAR", "Sugar" },
    { "SQUID_BOOTS", "Squid Boots" },
    { "STRING", "String" },
    { "SULPHUR", "Gunpowder" },
    { "SUN_PERSONALITY", "Sun Minion Skin" },
    { "STRONG_DRAGON_LEGGINGS", "Strong Dragon Leggings" },
    { "SUGAR_CANE", "Sugar Cane" },
    { "SUPERBOOM_TNT", "Superboom TNT" },
    { "SUPERIOR_DRAGON_BOOTS", "Superior Dragon Boots" },
    { "SUPERB_CARROT_CANDY", "Superb Carrot Candy" },
    { "SUPERIOR_DRAGON_HELMET", "Superior Dragon Helmet" },
    { "SUPERIOR_DRAGON_LEGGINGS", "Superior Dragon Leggings" },
    { "SUPERIOR_DRAGON_CHESTPLATE", "Superior Dragon Chestplate" },
    { "SUPERIOR_FRAGMENT", "Superior Dragon Fragment" },
    { "SURVIVOR_CUBE", "Survivor Cube" },
    { "STRONG_FRAGMENT", "Strong Dragon Fragment" },
    { "SWEET_AXE", "Sweet Axe" },
    { "TAIGA_BIOME_STICK", "Taiga Biome Stick" },
    { "SUPER_EGG", "Super Enchanted Egg" },
    { "TANK_MINER_CHESTPLATE", "Miner Chestplate" },
    { "TANK_MINER_BOOTS", "Miner Boots" },
    { "TANK_MINER_HELMET", "Miner Helmet" },
    { "TARANTULA_BOOTS", "Tarantula Boots" },
    { "TARANTULA_CHESTPLATE", "Tarantula Chestplate" },
    { "TARANTULA_HELMET", "Tarantula Helmet" },
    { "TARANTULA_LEGGINGS", "Tarantula Leggings" },
    { "TACTICIAN_SWORD", "Tactician's Sword" },
    { "TARANTULA_TALISMAN", "Tarantula Talisman" },
    { "TANK_MINER_LEGGINGS", "Miner Leggings" },
    { "TELEPORT_PAD", "Teleport Pad" },
    { "TEPID_GREEN_TEA", "Tepid Green Tea" },
    { "TARANTULA_SILK", "Tarantula Silk" },
    { "THIN_GLASS", "Glass Pane" },
    { "TIKI_TORCH", "Tiki Torch" },
    { "THE_SHREDDER", "Shredder" },
    { "TITANIC_EXP_BOTTLE", "Titanic Experience Bottle" },
    { "TNT", "TNT" },
    { "TORCH", "Torch" },
    { "TRAINING_DUMMY", "Training Dummy" },
    { "TRAPPED_CHEST", "Trapped Chest" },
    { "TRAP_DOOR", "Wooden Trapdoor" },
    { "TREECAPITATOR_AXE", "Treecapitator" },
    { "TARANTULA_WEB", "Tarantula Web" },
    { "TRIPWIRE_HOOK", "Tripwire Hook" },
    { "TRUE_ESSENCE", "True Essence" },
    { "TUTTI_FRUTTI_POISON", "Tutti-Frutti Flavored Poison" },
    { "TRICK_OR_TREAT_BAG", "Trick or Treat Bag" },
    { "UNDEAD_PERSONALITY", "Undead Minion Skin" },
    { "UNDEAD_CATALYST", "Undead Catalyst" },
    { "UNDEAD_SWORD", "Undead Sword" },
    { "UNSTABLE_DRAGON_CHESTPLATE", "Unstable Dragon Chestplate" },
    { "UNSTABLE_DRAGON_HELMET", "Unstable Dragon Helmet" },
    { "UNSTABLE_DRAGON_LEGGINGS", "Unstable Dragon Leggings" },
    { "UNSTABLE_DRAGON_BOOTS", "Unstable Dragon Boots" },
    { "TOXIC_ARROW_POISON", "Toxic Arrow Poison" },
    { "VAMPIRE_MASK", "Vampire Mask" },
    { "VIKING_TEAR", "Viking's Tear" },
    { "VILLAGE_TALISMAN", "Village Affinity Talisman" },
    { "VACCINE_TALISMAN", "Vaccine Talisman" },
    { "VOODOO_DOLL", "Voodoo Doll" },
    { "UNSTABLE_FRAGMENT", "Unstable Dragon Fragment" },
    { "VINE", "Vines" },
    { "WAND_OF_HEALING", "Wand of Healing" },
    { "WATCH", "Clock" },
    { "WAND_OF_RESTORATION", "Wand of Restoration" },
    { "WATER_BUCKET", "Water Bucket" },
    { "WATER_HYDRA_HEAD", "Water Hydra Head" },
    { "WATER_TROUGH", "Water Trough" },
    { "WAND_OF_MENDING", "Wand of Mending" },
    { "WATER_LILY", "Lily Pad" },
    { "WEAPON_RACK", "Weapon Rack" },
    { "WEB", "Web" },
    { "WEATHER_STICK", "Weather Stick" },
    { "WHALE_BAIT", "Whale Bait" },
    { "WEIRD_TUBA", "Weird Tuba" },
    { "WEAK_WOLF_CATALYST", "Weak Wolf Catalyst" },
    { "WHEAT", "Wheat" },
    { "WINTER_DISC", "Winter Disc" },
    { "WISE_DRAGON_BOOTS", "Wise Dragon Boots" },
    { "WISE_DRAGON_CHESTPLATE", "Wise Dragon Chestplate" },
    { "WISE_DRAGON_HELMET", "Wise Dragon Helmet" },
    { "WHITE_GIFT", "White Gift" },
    { "WISE_FRAGMENT", "Wise Dragon Fragment" },
    { "WITHER_ARTIFACT", "Wither Artifact" },
    { "WOLF_PAW", "Wolf Paw" },
    { "WOLF_RING", "Wolf Ring" },
    { "WINTER_ROD", "Winter Rod" },
    { "WITHER_BOW", "Wither Bow" },
    { "WOOD", "Oak Wood Plank" },
    { "WOOD:1", "Spruce Wood Plank" },
    { "WOOD:2", "Birch Wood Plank" },
    { "WOOD:3", "Jungle Wood Plank" },
    { "WISE_DRAGON_LEGGINGS", "Wise Dragon Leggings" },
    { "WOOD:4", "Acacia Wood Plank" },
    { "WOOD:5", "Dark Oak Wood Plank" },
    { "WOOD_BUTTON", "Wooden Button" },
    { "WOOD_AXE", "Wooden Axe" },
    { "WOOD_CHEST", "Wood Chest+" },
    { "WOOD_DOOR", "Oak Door" },
    { "WOOD_PLATE", "Wooden Pressure Plate" },
    { "WOOD_SINGULARITY", "Wood Singularity" },
    { "WOOD_SPADE", "Wooden Shovel" },
    { "WOOD_PICKAXE", "Wooden Pickaxe" },
    { "WOOD_STAIRS", "Oak Wood Stairs" },
    { "WOLF_TOOTH", "Wolf Tooth" },
    { "WOOD_STEP:1", "Spruce Wood Slab" },
    { "WOOD_STEP:2", "Birch Wood Slab" },
    { "WOOD_STEP:3", "Jungle Wood Slab" },
    { "WOOD_STEP:4", "Acacia Wood Slab" },
    { "WOOD_STEP:5", "Dark Oak Wood Slab" },
    { "WOOD_STEP", "Oak Wood Slab" },
    { "WOOD_HOE", "Wooden Hoe" },
    { "WOOL:1", "Orange Wool" },
    { "WOOL:10", "Purple Wool" },
    { "WOOL:11", "Blue Wool" },
    { "WOOL:12", "Brown Wool" },
    { "WOOL:13", "Green Wool" },
    { "WOOL:14", "Red Wool" },
    { "WOOL:15", "Black Wool" },
    { "WOOL:2", "Magenta Wool" },
    { "WOOL:3", "Light Blue Wool" },
    { "WOOL:4", "Yellow Wool" },
    { "WOOL:5", "Lime Wool" },
    { "WOOL:6", "Pink Wool" },
    { "WOOL:7", "Gray Wool" },
    { "WOOL:8", "Light Gray Wool" },
    { "WOOL:9", "Cyan Wool" },
    { "WORKBENCH", "Crafting Table" },
    { "WRAPPED_GIFT_FOR_JULIETTE", "Secret Gift for Juliette" },
    { "WRITTEN_BOOK", "Written Book" },
    { "WOOD_SWORD", "Wooden Sword" },
    { "YETI_ROD", "Yeti Rod" },
    { "WOOL", "White Wool" },
    { "YETI_SWORD", "Yeti Sword" },
    { "YELLOW_FLOWER", "Dandelion" },
    { "YOUNG_DRAGON_CHESTPLATE", "Young Dragon Chestplate" },
    { "YOUNG_DRAGON_HELMET", "Young Dragon Helmet" },
    { "YOUNG_DRAGON_LEGGINGS", "Young Dragon Leggings" },
    { "YOUNG_DRAGON_BOOTS", "Young Dragon Boots" },
    { "ZOMBIE_BOOTS", "Zombie Boots" },
    { "ZOMBIE_CHESTPLATE", "Zombie Chestplate" },
    { "ZOMBIE_GRAVE", "Zombie Grave" },
    { "ZOMBIE_ARTIFACT", "Zombie Artifact" },
    { "WOOD_TALISMAN", "Wood Affinity Talisman" },
    { "ZOMBIE_HAT", "Zombie Hat" },
    { "ZOMBIE_PICKAXE", "Zombie Pickaxe" },
    { "ZOMBIE_HEART", "Zombie's Heart" },
    { "ZOMBIE_LEGGINGS", "Zombie Leggings" },
    { "ZOMBIE_SWORD", "Zombie Sword" },
    { "ZOMBIE_RING", "Zombie Ring" },
    { "WOLF_TALISMAN", "Wolf Talisman" },
    { "ZOMBIE_TALISMAN", "Zombie Talisman" },
    { "YOUNG_FRAGMENT", "Young Dragon Fragment" },
    { "HOT_POTATO_BOOK", "Hot Potato Book" },
    { "SUMMONING_EYE", "Summoning Eye" },
    { "SUPER_COMPACTOR_3000", "Super Compactor 3000" },
    { "MAP:-37", "Map" },
    { "SKULL_ITEM:4", "Creeper Skull" },
    { "SUPER_MAGIC_MUSHROOM_SOUP", "Super Magical Mushroom Soup" },
    { "STAINED_GLASS_PANE:9", "Cyan Stained Glass Pane" },
    { "CARPET:1", "Orange Carpet" },
    { "SKULL_ITEM:1", "Wither Skeleton Skull" },
    { "PERSONAL_COMPACTOR_5000", "Personal Compactor 5000" },
    { "PERSONAL_COMPACTOR_6000", "Personal Compactor 6000" },
    { "PERSONAL_COMPACTOR_4000", "Personal Compactor 4000" },
    { "WOOL:0", "Wool" },
    { "PERFECT_LEGGINGS_6", "Perfect Leggings - Tier VI" }
};

#endif